(cl:defpackage mage-srv
  (:use )
  (:export
   "ENVIRONMENTAL_DATA"
   "<ENVIRONMENTAL_DATA-REQUEST>"
   "ENVIRONMENTAL_DATA-REQUEST"
   "<ENVIRONMENTAL_DATA-RESPONSE>"
   "ENVIRONMENTAL_DATA-RESPONSE"
   "MODEL_DATA"
   "<MODEL_DATA-REQUEST>"
   "MODEL_DATA-REQUEST"
   "<MODEL_DATA-RESPONSE>"
   "MODEL_DATA-RESPONSE"
   "NAVIGATION_DATA"
   "<NAVIGATION_DATA-REQUEST>"
   "NAVIGATION_DATA-REQUEST"
   "<NAVIGATION_DATA-RESPONSE>"
   "NAVIGATION_DATA-RESPONSE"
  ))

