# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mage/navigation_dataRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class navigation_dataRequest(genpy.Message):
  _md5sum = "4676fdac6556dac367c0e950a8916bb4"
  _type = "mage/navigation_dataRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 P_x
float64 P_y
float64 P_z

"""
  __slots__ = ['P_x','P_y','P_z']
  _slot_types = ['float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       P_x,P_y,P_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(navigation_dataRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.P_x is None:
        self.P_x = 0.
      if self.P_y is None:
        self.P_y = 0.
      if self.P_z is None:
        self.P_z = 0.
    else:
      self.P_x = 0.
      self.P_y = 0.
      self.P_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.P_x, _x.P_y, _x.P_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.P_x, _x.P_y, _x.P_z,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.P_x, _x.P_y, _x.P_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.P_x, _x.P_y, _x.P_z,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d = struct.Struct("<3d")
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mage/navigation_dataResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class navigation_dataResponse(genpy.Message):
  _md5sum = "e89223969d6bd9c1ea4e2cb69c635690"
  _type = "mage/navigation_dataResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 Ps_x
float64 Ps_y
float64 Ps_z
float64 Ps_course
float64 Pe_x
float64 Pe_y
float64 Pe_z
float64 Pe_course


"""
  __slots__ = ['Ps_x','Ps_y','Ps_z','Ps_course','Pe_x','Pe_y','Pe_z','Pe_course']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Ps_x,Ps_y,Ps_z,Ps_course,Pe_x,Pe_y,Pe_z,Pe_course

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(navigation_dataResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Ps_x is None:
        self.Ps_x = 0.
      if self.Ps_y is None:
        self.Ps_y = 0.
      if self.Ps_z is None:
        self.Ps_z = 0.
      if self.Ps_course is None:
        self.Ps_course = 0.
      if self.Pe_x is None:
        self.Pe_x = 0.
      if self.Pe_y is None:
        self.Pe_y = 0.
      if self.Pe_z is None:
        self.Pe_z = 0.
      if self.Pe_course is None:
        self.Pe_course = 0.
    else:
      self.Ps_x = 0.
      self.Ps_y = 0.
      self.Ps_z = 0.
      self.Ps_course = 0.
      self.Pe_x = 0.
      self.Pe_y = 0.
      self.Pe_z = 0.
      self.Pe_course = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8d.pack(_x.Ps_x, _x.Ps_y, _x.Ps_z, _x.Ps_course, _x.Pe_x, _x.Pe_y, _x.Pe_z, _x.Pe_course))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.Ps_x, _x.Ps_y, _x.Ps_z, _x.Ps_course, _x.Pe_x, _x.Pe_y, _x.Pe_z, _x.Pe_course,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8d.pack(_x.Ps_x, _x.Ps_y, _x.Ps_z, _x.Ps_course, _x.Pe_x, _x.Pe_y, _x.Pe_z, _x.Pe_course))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.Ps_x, _x.Ps_y, _x.Ps_z, _x.Ps_course, _x.Pe_x, _x.Pe_y, _x.Pe_z, _x.Pe_course,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8d = struct.Struct("<8d")
class navigation_data(object):
  _type          = 'mage/navigation_data'
  _md5sum = '0c2ecba2b4dea08339c547de7a1ab232'
  _request_class  = navigation_dataRequest
  _response_class = navigation_dataResponse
