(cl:in-package mage-msg)
(cl:export '(POS_N-VAL
          POS_N
          POS_E-VAL
          POS_E
          POS_D-VAL
          POS_D
          V_N_MS-VAL
          V_N_MS
          V_E_MS-VAL
          V_E_MS
          V_D_MS-VAL
          V_D_MS
          U-VAL
          U
          V-VAL
          V
          W-VAL
          W
          ROLL_DEG-VAL
          ROLL_DEG
          PITCH_DEG-VAL
          PITCH_DEG
          YAW_DEG-VAL
          YAW_DEG
          P_BODY-VAL
          P_BODY
          Q_BODY-VAL
          Q_BODY
          R_BODY-VAL
          R_BODY
          V_AIRSPEED-VAL
          V_AIRSPEED
          COURSE-VAL
          COURSE
          LAT_DEG-VAL
          LAT_DEG
          LONG_DEG-VAL
          LONG_DEG
          ALT_M-VAL
          ALT_M
          KI_X-VAL
          KI_X
          KI_Y-VAL
          KI_Y
          KI_Z-VAL
          KI_Z
))