# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mage/command_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class command_data(genpy.Message):
  _md5sum = "978bbee7b543b076983d5ef9268c14b8"
  _type = "mage/command_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 aileron
float32 elevator
float32 rudder
float32 throttle
float32 reached

"""
  __slots__ = ['aileron','elevator','rudder','throttle','reached']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       aileron,elevator,rudder,throttle,reached

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(command_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.aileron is None:
        self.aileron = 0.
      if self.elevator is None:
        self.elevator = 0.
      if self.rudder is None:
        self.rudder = 0.
      if self.throttle is None:
        self.throttle = 0.
      if self.reached is None:
        self.reached = 0.
    else:
      self.aileron = 0.
      self.elevator = 0.
      self.rudder = 0.
      self.throttle = 0.
      self.reached = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.aileron, _x.elevator, _x.rudder, _x.throttle, _x.reached))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.aileron, _x.elevator, _x.rudder, _x.throttle, _x.reached,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.aileron, _x.elevator, _x.rudder, _x.throttle, _x.reached))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.aileron, _x.elevator, _x.rudder, _x.throttle, _x.reached,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5f = struct.Struct("<5f")
