// Generated by gencpp from file mage/model_dataResponse.msg
// DO NOT EDIT!


#ifndef MAGE_MESSAGE_MODEL_DATARESPONSE_H
#define MAGE_MESSAGE_MODEL_DATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mage
{
template <class ContainerAllocator>
struct model_dataResponse_
{
  typedef model_dataResponse_<ContainerAllocator> Type;

  model_dataResponse_()
    : sensor_value()  {
    }
  model_dataResponse_(const ContainerAllocator& _alloc)
    : sensor_value(_alloc)  {
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _sensor_value_type;
  _sensor_value_type sensor_value;




  typedef boost::shared_ptr< ::mage::model_dataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mage::model_dataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct model_dataResponse_

typedef ::mage::model_dataResponse_<std::allocator<void> > model_dataResponse;

typedef boost::shared_ptr< ::mage::model_dataResponse > model_dataResponsePtr;
typedef boost::shared_ptr< ::mage::model_dataResponse const> model_dataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mage::model_dataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mage::model_dataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'mage': ['/home/daslab-server1/Rakshit/ros/src/mage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mage::model_dataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mage::model_dataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mage::model_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mage::model_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mage::model_dataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mage::model_dataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mage::model_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4d0076772e9386022da6cde2d0bccb7";
  }

  static const char* value(const ::mage::model_dataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4d0076772e93860ULL;
  static const uint64_t static_value2 = 0x22da6cde2d0bccb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::mage::model_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mage/model_dataResponse";
  }

  static const char* value(const ::mage::model_dataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mage::model_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] sensor_value\n\
\n\
";
  }

  static const char* value(const ::mage::model_dataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mage::model_dataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct model_dataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mage::model_dataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mage::model_dataResponse_<ContainerAllocator>& v)
  {
    s << indent << "sensor_value[]" << std::endl;
    for (size_t i = 0; i < v.sensor_value.size(); ++i)
    {
      s << indent << "  sensor_value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sensor_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGE_MESSAGE_MODEL_DATARESPONSE_H
