// Generated by gencpp from file mage/navigation_data.msg
// DO NOT EDIT!


#ifndef MAGE_MESSAGE_NAVIGATION_DATA_H
#define MAGE_MESSAGE_NAVIGATION_DATA_H

#include <ros/service_traits.h>


#include <mage/navigation_dataRequest.h>
#include <mage/navigation_dataResponse.h>


namespace mage
{

struct navigation_data
{

typedef navigation_dataRequest Request;
typedef navigation_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct navigation_data
} // namespace mage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mage::navigation_data > {
  static const char* value()
  {
    return "ed4b37e8ae38706e3abd169327717ac6";
  }

  static const char* value(const ::mage::navigation_data&) { return value(); }
};

template<>
struct DataType< ::mage::navigation_data > {
  static const char* value()
  {
    return "mage/navigation_data";
  }

  static const char* value(const ::mage::navigation_data&) { return value(); }
};


// service_traits::MD5Sum< ::mage::navigation_dataRequest> should match 
// service_traits::MD5Sum< ::mage::navigation_data > 
template<>
struct MD5Sum< ::mage::navigation_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mage::navigation_data >::value();
  }
  static const char* value(const ::mage::navigation_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mage::navigation_dataRequest> should match 
// service_traits::DataType< ::mage::navigation_data > 
template<>
struct DataType< ::mage::navigation_dataRequest>
{
  static const char* value()
  {
    return DataType< ::mage::navigation_data >::value();
  }
  static const char* value(const ::mage::navigation_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mage::navigation_dataResponse> should match 
// service_traits::MD5Sum< ::mage::navigation_data > 
template<>
struct MD5Sum< ::mage::navigation_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mage::navigation_data >::value();
  }
  static const char* value(const ::mage::navigation_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mage::navigation_dataResponse> should match 
// service_traits::DataType< ::mage::navigation_data > 
template<>
struct DataType< ::mage::navigation_dataResponse>
{
  static const char* value()
  {
    return DataType< ::mage::navigation_data >::value();
  }
  static const char* value(const ::mage::navigation_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAGE_MESSAGE_NAVIGATION_DATA_H
