// Generated by gencpp from file mage/navigation_dataResponse.msg
// DO NOT EDIT!


#ifndef MAGE_MESSAGE_NAVIGATION_DATARESPONSE_H
#define MAGE_MESSAGE_NAVIGATION_DATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mage
{
template <class ContainerAllocator>
struct navigation_dataResponse_
{
  typedef navigation_dataResponse_<ContainerAllocator> Type;

  navigation_dataResponse_()
    : Ps_x(0.0)
    , Ps_y(0.0)
    , Ps_z(0.0)
    , Ps_course(0.0)
    , Pe_x(0.0)
    , Pe_y(0.0)
    , Pe_z(0.0)
    , Pe_course(0.0)  {
    }
  navigation_dataResponse_(const ContainerAllocator& _alloc)
    : Ps_x(0.0)
    , Ps_y(0.0)
    , Ps_z(0.0)
    , Ps_course(0.0)
    , Pe_x(0.0)
    , Pe_y(0.0)
    , Pe_z(0.0)
    , Pe_course(0.0)  {
    }



   typedef float _Ps_x_type;
  _Ps_x_type Ps_x;

   typedef float _Ps_y_type;
  _Ps_y_type Ps_y;

   typedef float _Ps_z_type;
  _Ps_z_type Ps_z;

   typedef float _Ps_course_type;
  _Ps_course_type Ps_course;

   typedef float _Pe_x_type;
  _Pe_x_type Pe_x;

   typedef float _Pe_y_type;
  _Pe_y_type Pe_y;

   typedef float _Pe_z_type;
  _Pe_z_type Pe_z;

   typedef float _Pe_course_type;
  _Pe_course_type Pe_course;




  typedef boost::shared_ptr< ::mage::navigation_dataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mage::navigation_dataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct navigation_dataResponse_

typedef ::mage::navigation_dataResponse_<std::allocator<void> > navigation_dataResponse;

typedef boost::shared_ptr< ::mage::navigation_dataResponse > navigation_dataResponsePtr;
typedef boost::shared_ptr< ::mage::navigation_dataResponse const> navigation_dataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mage::navigation_dataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mage::navigation_dataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'mage': ['/home/daslab-server1/Rakshit/ros/src/mage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mage::navigation_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mage::navigation_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mage::navigation_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mage::navigation_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mage::navigation_dataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mage::navigation_dataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mage::navigation_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "774911f6abf9912532bc825396132fdf";
  }

  static const char* value(const ::mage::navigation_dataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x774911f6abf99125ULL;
  static const uint64_t static_value2 = 0x32bc825396132fdfULL;
};

template<class ContainerAllocator>
struct DataType< ::mage::navigation_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mage/navigation_dataResponse";
  }

  static const char* value(const ::mage::navigation_dataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mage::navigation_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Ps_x\n\
float32 Ps_y\n\
float32 Ps_z\n\
float32 Ps_course\n\
float32 Pe_x\n\
float32 Pe_y\n\
float32 Pe_z\n\
float32 Pe_course\n\
\n\
";
  }

  static const char* value(const ::mage::navigation_dataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mage::navigation_dataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Ps_x);
      stream.next(m.Ps_y);
      stream.next(m.Ps_z);
      stream.next(m.Ps_course);
      stream.next(m.Pe_x);
      stream.next(m.Pe_y);
      stream.next(m.Pe_z);
      stream.next(m.Pe_course);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct navigation_dataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mage::navigation_dataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mage::navigation_dataResponse_<ContainerAllocator>& v)
  {
    s << indent << "Ps_x: ";
    Printer<float>::stream(s, indent + "  ", v.Ps_x);
    s << indent << "Ps_y: ";
    Printer<float>::stream(s, indent + "  ", v.Ps_y);
    s << indent << "Ps_z: ";
    Printer<float>::stream(s, indent + "  ", v.Ps_z);
    s << indent << "Ps_course: ";
    Printer<float>::stream(s, indent + "  ", v.Ps_course);
    s << indent << "Pe_x: ";
    Printer<float>::stream(s, indent + "  ", v.Pe_x);
    s << indent << "Pe_y: ";
    Printer<float>::stream(s, indent + "  ", v.Pe_y);
    s << indent << "Pe_z: ";
    Printer<float>::stream(s, indent + "  ", v.Pe_z);
    s << indent << "Pe_course: ";
    Printer<float>::stream(s, indent + "  ", v.Pe_course);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGE_MESSAGE_NAVIGATION_DATARESPONSE_H
