(cl:in-package mage-srv)
(cl:export '(UAV_TAG-VAL
          UAV_TAG
          RESPONSE-VAL
          RESPONSE
          ROWS-VAL
          ROWS
          COLUMNS-VAL
          COLUMNS
          BV1-VAL
          BV1
          BV2-VAL
          BV2
          BV3-VAL
          BV3
          BV4-VAL
          BV4
          BV5-VAL
          BV5
          BV6-VAL
          BV6
          BV7-VAL
          BV7
          BV8-VAL
          BV8
          BV9-VAL
          BV9
          W-VAL
          W
))