// Generated by gencpp from file mage/environmental_dataResponse.msg
// DO NOT EDIT!


#ifndef MAGE_MESSAGE_ENVIRONMENTAL_DATARESPONSE_H
#define MAGE_MESSAGE_ENVIRONMENTAL_DATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mage
{
template <class ContainerAllocator>
struct environmental_dataResponse_
{
  typedef environmental_dataResponse_<ContainerAllocator> Type;

  environmental_dataResponse_()
    : sensor_value(0.0)  {
    }
  environmental_dataResponse_(const ContainerAllocator& _alloc)
    : sensor_value(0.0)  {
    }



   typedef double _sensor_value_type;
  _sensor_value_type sensor_value;




  typedef boost::shared_ptr< ::mage::environmental_dataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mage::environmental_dataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct environmental_dataResponse_

typedef ::mage::environmental_dataResponse_<std::allocator<void> > environmental_dataResponse;

typedef boost::shared_ptr< ::mage::environmental_dataResponse > environmental_dataResponsePtr;
typedef boost::shared_ptr< ::mage::environmental_dataResponse const> environmental_dataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mage::environmental_dataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mage::environmental_dataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'mage': ['/home/daslab-server1/Rakshit/ros/src/mage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mage::environmental_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mage::environmental_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mage::environmental_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mage::environmental_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mage::environmental_dataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mage::environmental_dataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mage::environmental_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f5aa4de86352878fa3cfbaa0a01b9c4";
  }

  static const char* value(const ::mage::environmental_dataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f5aa4de86352878ULL;
  static const uint64_t static_value2 = 0xfa3cfbaa0a01b9c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mage::environmental_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mage/environmental_dataResponse";
  }

  static const char* value(const ::mage::environmental_dataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mage::environmental_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 sensor_value\n\
\n\
";
  }

  static const char* value(const ::mage::environmental_dataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mage::environmental_dataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct environmental_dataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mage::environmental_dataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mage::environmental_dataResponse_<ContainerAllocator>& v)
  {
    s << indent << "sensor_value: ";
    Printer<double>::stream(s, indent + "  ", v.sensor_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAGE_MESSAGE_ENVIRONMENTAL_DATARESPONSE_H
