// Generated by gencpp from file mage/model_data.msg
// DO NOT EDIT!


#ifndef MAGE_MESSAGE_MODEL_DATA_H
#define MAGE_MESSAGE_MODEL_DATA_H

#include <ros/service_traits.h>


#include <mage/model_dataRequest.h>
#include <mage/model_dataResponse.h>


namespace mage
{

struct model_data
{

typedef model_dataRequest Request;
typedef model_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct model_data
} // namespace mage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mage::model_data > {
  static const char* value()
  {
    return "068069642642797e324175cfa8a60121";
  }

  static const char* value(const ::mage::model_data&) { return value(); }
};

template<>
struct DataType< ::mage::model_data > {
  static const char* value()
  {
    return "mage/model_data";
  }

  static const char* value(const ::mage::model_data&) { return value(); }
};


// service_traits::MD5Sum< ::mage::model_dataRequest> should match 
// service_traits::MD5Sum< ::mage::model_data > 
template<>
struct MD5Sum< ::mage::model_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mage::model_data >::value();
  }
  static const char* value(const ::mage::model_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mage::model_dataRequest> should match 
// service_traits::DataType< ::mage::model_data > 
template<>
struct DataType< ::mage::model_dataRequest>
{
  static const char* value()
  {
    return DataType< ::mage::model_data >::value();
  }
  static const char* value(const ::mage::model_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mage::model_dataResponse> should match 
// service_traits::MD5Sum< ::mage::model_data > 
template<>
struct MD5Sum< ::mage::model_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mage::model_data >::value();
  }
  static const char* value(const ::mage::model_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mage::model_dataResponse> should match 
// service_traits::DataType< ::mage::model_data > 
template<>
struct DataType< ::mage::model_dataResponse>
{
  static const char* value()
  {
    return DataType< ::mage::model_data >::value();
  }
  static const char* value(const ::mage::model_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAGE_MESSAGE_MODEL_DATA_H
